pangeo:
  jupyterhub:
    scheduling:
      userPods:
        nodeAffinity:
          matchNodePurpose: require
      corePods:
        nodeAffinity:
          matchNodePurpose: require
    singleuser:
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command: ["sh", "-c", "id && chown 1000:1000 /home/jovyan && ls -lhd /home/jovyan"]
          securityContext:
            runAsUser: 0
          volumeMounts:
          - name: home
            mountPath: /home/jovyan
            subPath: "home/hydro.pangeo.io/{username}"
      storage:
        type: static
        static:
          pvcName: home-nfs
          subPath: "home/hydro.pangeo.io/{username}"
      cloudMetadata:
        enabled: true
    auth:
      github:
        org_whitelist:
          - pangeo-data
      admin:
        access: true
        users:
          - jhamman
          - bartnijssen
          - arbennett
    hub:
      resources:
        requests:
          cpu: "0.25"
          memory: 0.5Gi
        limits:
          cpu: "1.25"
          memory: 1Gi
      extraConfig:
        profile_list: |
          c.KubeSpawner.profile_list = [
            {
                'display_name': 'standard ** CUAHSI Snow Hydrology Students **',
                'kubespawner_override': {
                    'cpu_limit': 1,
                    'cpu_guarantee': 0.5,
                    'mem_limit': '6G',
                    'mem_guarantee': '4G',
                }
            },
            {
                'display_name': 'standard (n1-highmem-4 | 4 cores, 24GB)',
                'kubespawner_override': {
                    'cpu_limit': 4,
                    'cpu_guarantee': 4,
                    'mem_limit': '24G',
                    'mem_guarantee': '24G',
                }
            },
            {
                'display_name': 'Pangeo Env - standard (n1-highmem-4 | 4 cores, 24GB)',
                'kubespawner_override': {
                    'cpu_limit': 4,
                    'cpu_guarantee': 4,
                    'mem_limit': '24G',
                    'mem_guarantee': '24G',
                    'image': 'pangeo/pangeo-notebook:latest',
                }
            },
            {
                'display_name': 'Pangeo GPU-ML Env - standard (n1-standard-4 | 4 cores, 15GB | 1 GPU)',
                'kubespawner_override': {
                    'cpu_limit': 4,
                    'cpu_guarantee': 1,
                    'mem_limit': '15G',
                    'mem_guarantee': '15G',
                    'image': 'pangeo/ml-notebook:latest',
                    'extra_resource_limits': {"nvidia.com/gpu": "1"},
                }
            },
            {
                'display_name': 'Pangeo R-Hydro Env',
                'kubespawner_override': {
                    'cpu_limit': 1,
                    'cpu_guarantee': 1,
                    'mem_limit': '8G',
                    'mem_guarantee': '8G',
                    'image': 'jupyter/r-notebook',
                }
            },
          ]
        customPodHook: |
          c.JupyterHub.template_paths = ['/usr/local/share/jupyterhub/custom_templates/']
          c.JupyterHub.template_vars = {
            'pangeo_hub_title': 'hydro.pangeo.io',
            'pangeo_hub_subtitle': 'a community hub for hydrologic research',
            'pangeo_welcome': """Welcome to hydro.pangeo.io. This hub lives in Google Cloud region <code>us-central1-b</code>. It is maintained by the <a href="http://pangeo.io">Pangeo project</a> and supported by a grant from the National Science Foundation (NSF award 1740648), which includes a direct award of cloud credits from Google Cloud. The hub's configuration is stored in the github repository <a href="https://github.com/pangeo-data/pangeo-cloud-federation/">https://github.com/pangeo-data/pangeo-cloud-federation/</a>. To provide feedback and report any technical problems, please use the <a href="https://github.com/pangeo-data/pangeo-cloud-federation//issues">github issue tracker</a>.""",
            'announcement': 'hydro.pangeo.io is being decommissioned on Monday, June 22, 2020. Please see <a href="https://discourse.pangeo.io/t/migration-of-ocean-pangeo-io-user-accounts/644">Discourse</a> for more information.'
          }

      extraVolumes:
        - name: custom-templates
          gitRepo:
            repository: "https://github.com/pangeo-data/pangeo-custom-jupyterhub-templates.git"
            revision: "39962614b3df4ca86efb29712f7e67c51308d25b"
      extraVolumeMounts:
        - mountPath: /usr/local/share/jupyterhub/custom_templates
          name: custom-templates
          subPath: "pangeo-custom-jupyterhub-templates/templates"
        - mountPath: /usr/local/share/jupyterhub/static/extra-assets
          name: custom-templates
          subPath: "pangeo-custom-jupyterhub-templates/extra-assets"

homeDirectories:
  nfs:
    enabled: true
    serverPath: "/homes"
    # Output from gcloud beta filestore instances describe dev-home --location=us-central1-b
    serverIP: 10.171.161.186
    serverName: test
