apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: pangeo-deploy
version: 0.1.0
dependencies:
  - name: pangeo
    version: "v0.2.2-n059.h1730652"
    repository: https://pangeo-data.github.io/helm-chart/
    import-values:
      - child: rbac
        parent: rbac
  - name: prometheus
    version: 11.6.0
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: grafana
    version: 5.3.0
    repository: https://kubernetes-charts.storage.googleapis.com
