name: notebook
channels:
  - conda-forge
dependencies:
  - pangeo-notebook=2020.07.03
  - awscli
  - boto3
  - datashader
  - fsspec
  - gcsfs
  - geopandas
  - geoviews
  - h5netcdf
  - h5py
  - hvplot
  - intake
  - intake-stac
  - intake-xarray
  - ipykernel
  - ipyleaflet
  - ipywidgets
  - jq
  - libgdal
  - matplotlib-base
  - nb_conda_kernels
  - pandas
  - panel
  - pip
  - pystac
  - rasterio
  - requests
  - rio-cogeo
  - s3fs
  - sat-search
  - sat-stac
  - xarray
  - zarr
